const campname = [
  { name: "Emerald Forest Camp" },
  { name: "Golden Savanna Camp" },
  { name: "Whispering Highland Camp" },
  { name: "Sunset Oceanview Camp" },
  { name: "Tranquil Lakeside Retreat" },
  { name: "Rustic Riverside Camp" },
  { name: "Sacred Rainforest Lodge" },
  { name: "Hidden Mangrove Haven" },
  { name: "Sacred Ancient Camp" },
  { name: "Forest Heritage Camp" },
  { name: "Rocky Canyon Camp" },
  { name: "Hidden Valley Camp" },
  { name: "Sacred Hillside Camp" },
  { name: "Palm Island Camp" },
  { name: "Sunrise Hillside Camp" },
  { name: "Sunrise Lakeside Haven" },
  { name: "Sunset Riverside Camp" },
  { name: "Wildlife Plateau Camp" },
  { name: "Rustic Countryside Camp" },
  { name: "Tranquil Marshland Camp" },
  { name: "Serene Forest Retreat" },
  { name: "Rainforest Jungle Camp" },
  { name: "Eco Coastal Camp" },
  { name: "Starlight Desert Camp" },
  { name: "Emerald Valley Camp" },
  { name: "Whispering Canyon Camp" },
  { name: "Cliffside Oceanview Camp" },
  { name: "Whispering Savanna Camp" },
  { name: "Golden Sunrise Camp" },
  { name: "Sunset at Ikogosi" },
  { name: "Emerald Idanre Hills Camp" },
  { name: "Starlight Erin-Ijesha Camp" },
  { name: "Highland Jos Plateau Camp" },
  { name: "Coastal Badagry Camp" },
  { name: "Oceanview Tarkwa Bay Camp" },
  { name: "Rustic Kajuru Camp" },
  { name: "Sacred Osun Grove Camp" },
  { name: "Rainforest Gurara Falls Camp" },
  { name: "Lakeside Kainji Camp" },
  { name: "Highland Mambilla Camp" },
  { name: "Jungle Okomu Camp" },
  { name: "Cliffside Aso Rock Camp" },
  { name: "Palm Bonny Island Camp" },
  { name: "Coastal Calabar Camp" },
  { name: "Riverside Epe Camp" },
  { name: "Golden Argungu Camp" },
  { name: "Lakeside Oguta Camp" },
  { name: "Hidden Ngwo Forest Camp" },
  { name: "Heritage Kajuru Castle Camp" },
  { name: "Tranquil Jabi Lake Camp" },
  { name: "Oceanview Ibeno Camp" },
  { name: "Sunrise Bar Beach Camp" },
  { name: "Emerald Ikeja Camp" },
  { name: "Riverside Lokoja Camp" },
  { name: "Marshland Makoko Camp" },
  { name: "Hidden Ogbunike Caves Camp" },
  { name: "Savanna Kwali Camp" },
  { name: "Highland Shere Hills Camp" },
  { name: "Valley Keffi Camp" },
];

module.exports = campname;
