const description = [
  "Serene Erin-Ijesha – a peaceful haven amid cascading waterfalls and lush greenery, where crystal-clear streams tumble over ancient rocks, inviting campers to relax in the soothing mist and vibrant forest ambiance, ideal for nature enthusiasts seeking tranquility and rejuvenation.",
  "Golden Jos Plateau – a radiant campsite perched on expansive highland meadows bathed in warm sunlight, surrounded by rolling hills and wildflowers, offering breathtaking vistas and crisp air perfect for serene hikes and stargazing under vast, clear skies.",
  "Hidden Badagry – a secluded coastal retreat nestled among whispering palms and historic sands, where gentle waves lap at the shore and ancient ruins whisper tales of the past, creating an inviting escape for those seeking peaceful reflection and natural beauty.",
  "Sacred Tarkwa Bay – a mystical island sanctuary with pristine beaches and sacred groves, where turquoise waters meet soft sands under swaying palms, providing a tranquil spot for meditation and unwinding in harmony with the rhythmic ocean breeze.",
  "Eco Kajuru – an environmentally conscious haven in rugged terrains dotted with ancient castles and verdant valleys, where sustainable camping blends with wildlife sightings, offering a refreshing retreat for eco-adventurers and peace-seekers alike.",
  "Starlight Osun Grove – a celestial woodland escape under endless night skies, enveloped by sacred trees and gentle streams that glow with bioluminescent wonders, perfect for campers desiring quiet nights filled with stars and the soft symphony of nature.",
  "Valley Gurara Falls – a lush valley campsite beside thundering waterfalls and misty gorges, where emerald pools invite refreshing dips and surrounding forests teem with life, creating an idyllic setting for peaceful getaways and immersive natural experiences.",
  "Canyon Kainji – a dramatic canyon retreat overlooking vast reservoirs and rocky cliffs, with serene waters reflecting golden sunsets and abundant wildlife, offering a rustic haven for those yearning for solitude and the raw beauty of untamed landscapes.",
  "Cliffside Mambilla – a breathtaking cliffside perch on high plateaus with sweeping views of misty valleys and tea plantations, where cool breezes carry the scent of wild herbs, inviting campers to embrace the serenity of elevated wilderness.",
  "Whispering Okomu – an enchanting rainforest hideaway where ancient trees whisper secrets amid lush undergrowth and winding paths, home to diverse wildlife and tranquil clearings, perfect for nature lovers seeking a whispering escape into biodiversity.",
  "Emerald Aso Rock – a verdant campsite at the base of majestic rock formations and emerald hills, where fresh springs and panoramic views create a serene atmosphere, ideal for peaceful retreats and explorations in Nigeria's heartland.",
  "Countryside Bonny Island – a charming rural island escape surrounded by mangrove-lined creeks and fertile countryside, with gentle tides and vibrant birdlife, offering a welcoming spot for campers to unwind in natural simplicity and coastal charm.",
  "Coastal Calabar – a serene coastal haven with golden beaches and lush hinterlands, where the ocean's rhythm harmonizes with tropical breezes, providing an inviting paradise for relaxation and discovering hidden coves along the shoreline.",
  "Island Epe – a tranquil island retreat amid serene lagoons and palm-fringed shores, where calm waters reflect vibrant sunsets and local wildlife thrives, creating a peaceful sanctuary for those seeking island solitude and natural wonders.",
  "Desert Argungu – a mystical desert oasis campsite near ancient fishing grounds and golden dunes, where starry nights and cool oases offer respite, inviting adventurers to experience the quiet magic of arid landscapes and cultural heritage.",
];

module.exports = { description };
